preserve_hierarchy: true
files:
  - source: /docs/es/coding/devops/*.md
    translation: /docs/%two_letters_code%/coding/devops/%original_file_name%
  - source: /docs/es/coding/architecture/*.md
    translation: /docs/%two_letters_code%/coding/architecture/%original_file_name%
  - source: /docs/es/coding/languages/*.md
    translation: /docs/%two_letters_code%/coding/languages/%original_file_name%
  - source: /docs/es/coding/*.md
    translation: /docs/%two_letters_code%/coding/%original_file_name%
  - source: /docs/es/platform/channels/*.md
    translation: /docs/%two_letters_code%/platform/channels/%original_file_name%
  - source: /docs/es/platform/infrastructure/*.md
    translation: /docs/%two_letters_code%/platform/infrastructure/%original_file_name%
  - source: /docs/es/platform/core/integrations/*.md
    translation: /docs/%two_letters_code%/platform/core/integrations/%original_file_name%
  - source: /docs/es/platform/core/*.md
    translation: /docs/%two_letters_code%/platform/core/%original_file_name%
  - source: /docs/es/platform/tutorials/*.md
    translation: /docs/%two_letters_code%/platform/tutorials/%original_file_name%
  - source: /docs/es/platform/commerce/*.md
    translation: /docs/%two_letters_code%/platform/commerce/%original_file_name%
  - source: /docs/es/platform/insights/*.md
    translation: /docs/%two_letters_code%/platform/insights/%original_file_name%
  - source: /docs/es/platform/content/*.md
    translation: /docs/%two_letters_code%/platform/content/%original_file_name%
  - source: /docs/es/platform/customers/*.md
    translation: /docs/%two_letters_code%/platform/customers/%original_file_name%
  - source: /docs/es/platform/*.md
    translation: /docs/%two_letters_code%/platform/%original_file_name%
  - source: /docs/es/legal/*.md
    translation: /docs/%two_letters_code%/legal/%original_file_name%
  - source: /docs/es/connect/*.md
    translation: /docs/%two_letters_code%/connect/%original_file_name%
  - source: /docs/es/widgets/onboarding/*.md
    translation: /docs/%two_letters_code%/widgets/onboarding/%original_file_name%
  - source: /docs/es/widgets/insurance-retail/*.md
    translation: /docs/%two_letters_code%/widgets/insurance-retail/%original_file_name%
  - source: /docs/es/widgets/retail/*.md
    translation: /docs/%two_letters_code%/widgets/retail/%original_file_name%
  - source: /docs/es/widgets/guides/*.md
    translation: /docs/%two_letters_code%/widgets/guides/%original_file_name%
  - source: /docs/es/widgets/investments/*.md
    translation: /docs/%two_letters_code%/widgets/investments/%original_file_name%
  - source: /docs/es/widgets/insurance-brokers/*.md
    translation: /docs/%two_letters_code%/widgets/insurance-brokers/%original_file_name%
  - source: /docs/es/widgets/*.md
    translation: /docs/%two_letters_code%/widgets/%original_file_name%
  - source: /docs/es/brand/documents/*.md
    translation: /docs/%two_letters_code%/brand/documents/%original_file_name%
  - source: /docs/es/brand/*.md
    translation: /docs/%two_letters_code%/brand/*.md
