
name: Index Algolia
on:

  schedule:
  - cron: "00 1 1,15 * *"
  
  workflow_dispatch:
  

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get the content of algolia.json as config
        id: algolia_config
        run: echo "config=$(cat algolia.json | jq -r tostring)" >> $GITHUB_OUTPUT

      - name: Push indices to Algolia
        uses: signcl/docsearch-scraper-action@master
        env:
          APPLICATION_ID: TEEU706UKD
          API_KEY: e445aba903f3930fd3b7748786a7532d
          CONFIG: ${{ steps.algolia_config.outputs.config }}
